name: Build Builder Image

on:
  push:
    branches: [main]
    paths:
      - 'containers/Dockerfile'
      - '.github/workflows/push-builder.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f containers/Dockerfile -t ghcr.io/${{ github.repository_owner }}/slangd-cross-builder:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/slangd-cross-builder:latest
