name: Release Build

on:
  workflow_dispatch:

jobs:
  build-extension:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/slangd-cross-builder:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Show tool versions
        run: |
          which clang && clang --version
          which clang++ && clang++ --version
          which bazel && bazel --version

      - name: Install npm dependencies
        working-directory: editor/vscode
        run: npm ci

      - name: Build and package VSIX
        working-directory: editor/vscode
        run: npm run package:ci

      - name: Upload packaged .vsix
        uses: actions/upload-artifact@v4
        with:
          name: systemverilog-extension
          path: editor/vscode/*.vsix
