name: Check Code Style

on:
  push:
    branches: [main]
    paths:
      - "**.cpp"
      - "**.hpp"
      - ".clang-format"
      - ".github/workflows/style.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.cpp"
      - "**.hpp"
      - ".clang-format"
      - ".github/workflows/style.yml"

jobs:
  clang-format-check:
    name: C++ Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 19
